### ISSUE TITLE
Add the ability to label a specific input/output for easier parsing of events

### ISSUE THREAD

**Issue by austinscreations** [sumnerboy12/UIO#2]
a possible future feature 

maybe have it settable of what sensor is attached to help dictate the topic. 
say
fire, CO, motion, door, window, etc?

**Comment by sumnerboy12** [comment]
What about adding a new config topic option `/label`?

So you publish a label to `usm/conf/UIO-ABCDEF/6/label` and when an event happens on that port/channel the label is included in the payload;

```
{"PORT":2, "CHANNEL":3, "INDEX":6, "TYPE":"CONTACT", "EVENT":"OPEN", "LABEL":"YOUR LABEL"}
```

**Comment by austinscreations** [comment]
That be a good option.

would it be an array with items or say fully custom where one might put, "kitchen alarm" or "living room motion"
although i realize now doing it as fully custom might use far too much space and not be very KISS.

**Comment by sumnerboy12** [comment]
I was thinking a custom string - with a max length of say 16 chars? For the 24 port USM, that is 96 * 16 = 1536 bytes tho, so it will quickly start to chew up memory. 

I am not convinced we need it - it is a nice-to-have and sounds useful, but I think in reality would be very rarely used. You are always going to bind the UIO/USM MQTT topics to another system, NodeRED or HA or openHAB, and these systems will contain all the labelling and tagging needed.

**Comment by austinscreations** [comment]
definitely a nicety. 

so for now i think we can leave it and have it as an idea later.

**Comment by sumnerboy12** [comment]
@austinscreations could you re-add this to the new repo please? I will close this issue as this repo is about to be removed,

https://github.com/SuperHouse/OXRS-SHA-SmokeDetector-ESP32-FW
